export const type = `
  
  type NisaCollection {
    _id: String
    emr_id: Int
    patient_first_name: String
    patient_last_name: String
    patient_middle_name: String
    patient_legacy_number: String
    date_of_birth: String
    phone_number: String
    sex: String
    patient_title: String
    provider_or_scheme: String
    patient_email: String
    patient_nationality: Int
    patient_occupation: String
    patient_work_address: String
    patient_address: String
    patient_is_deceased: Boolean
    patient_is_active: Boolean
    record_date: String
    report_type: String
    encounter_id: Int
    service_center: String
    hospital_id: Int
    referral_id: String
    theatre_id: String
    surgeon_id: String
    bodypart_id: String
    anesthesiologist_id: String
    lab_template_data_label: String
    lab_result_data_value: String
    lab_template_data_lab_method_id: Int
    lab_template_data_reference: String
    lab_template_data_lab_template_id: Int
    lab_result_id: Int
    lab_template_id: Int
    lab_result_patient_lab_id: Int
    lab_result_approved: Boolean
    lab_result_abnormal_lab_value: Int
    lab_result_approved_by: String
    lab_result_approved_date: String
    lab__patient_labs_patient_id: Int
    lab__patient_labs_test_id: Int
    lab__patient_labs_specimen_date: String
    lab__patient_labs_lab_group_id: String
    lab__patient_labs_test_date: String
    lab__patient_labs_test_notes: String
    lab__patient_labs_status: String
    labtests_config_name: String
    regimen_drug_name: String
    regimen_drug_generic_name: String
    regimen_description: String
    regimen_weight: String
    regimen_form: String
    regimen_drug_id: Int
    regimen_quantity: Int
    regimen_request_time: String
    regimen_filled_time: String
    regimen_completed_time: String
    regimen_status: String
    regimen_prescribed_by: String
    regimen_note: String
    regimen_refill_off: String
    regimen_requested_by: String
    radiology_scan_name: String
    radiology_request_note: String
    radiology_request_date: String
    radiology_is_approved: Boolean
    radiology_approved_date: String
    radiology_status: Boolean
    radiology_cancelled: Boolean
    radio_cancel_date: String
    patient_diagnoses_date_of_entry: String
    patient_diagnoses_diag_type: String
    patient_diagnoses_active: Boolean
    patient_diagnoses_severity: String
    patient_diagnoses_diagnosisNote: String
    patient_diagnoses_diagnosis: String
    patient_diagnoses_status: String
    diagnoses_id: Int
    diagnoses_code: String
    diagnoses_type: String
    diagnoses_case: String
    diagnoses_parent_id: String
    diagnoses_oi: Int
    procedure_id: Int
    procedure_name: String
    procedure_icd_code: String
    procedure_description: String
    patient_procedure_id: Int
    patient_procedure_request_note: String
    patient_procedure_closing_text: String
    scheduled_on: String
    scheduled_by: String
    patient_procedure_time_started: String
    patient_procedure_time_start: String
    patient_procedure_time_stop: String
    patient_procedure_requested_by: String
    patient_procedure_note: String
    patient_procedure_note_time: String
    patient_procedure_note_type: String
    patient_procedure_request_date: String
    patient_procedure_status: String
    consultation_date_of_entry: String
    consultation_diagnoses: String
    consultation_note_type: String
    consultation_reason: String
    consultation_doctors_name: String
    patient_procedure_nursing_task_id: String
    patient_procedure_nursing_service: String
    vital_sign_type: String
    vital_sign_value: String
    vital_sign_unit: String
    vital_sign_min_val: String
    vital_sign_read_date: String
  }

  type NisaCollectionQueryResults {
    NisaCollections: [NisaCollection]
    Meta: QueryResultsMetadata
  }

  type NisaCollectionSingleQueryResult {
    NisaCollection: NisaCollection
  }

  type NisaCollectionMutationResult {
    success: Boolean
    NisaCollection: NisaCollection
  }

  type NisaCollectionMutationResultMulti {
    success: Boolean
    NisaCollections: [NisaCollection]
  }

  type NisaCollectionBulkMutationResult {
    success: Boolean
  }

  input NisaCollectionInput {
    _id: String
    emr_id: Int
    patient_first_name: String
    patient_last_name: String
    patient_middle_name: String
    patient_legacy_number: String
    date_of_birth: String
    phone_number: String
    sex: String
    patient_title: String
    provider_or_scheme: String
    patient_email: String
    patient_nationality: Int
    patient_occupation: String
    patient_work_address: String
    patient_address: String
    patient_is_deceased: Boolean
    patient_is_active: Boolean
    record_date: String
    report_type: String
    encounter_id: Int
    service_center: String
    hospital_id: Int
    referral_id: String
    theatre_id: String
    surgeon_id: String
    bodypart_id: String
    anesthesiologist_id: String
    lab_template_data_label: String
    lab_result_data_value: String
    lab_template_data_lab_method_id: Int
    lab_template_data_reference: String
    lab_template_data_lab_template_id: Int
    lab_result_id: Int
    lab_template_id: Int
    lab_result_patient_lab_id: Int
    lab_result_approved: Boolean
    lab_result_abnormal_lab_value: Int
    lab_result_approved_by: String
    lab_result_approved_date: String
    lab__patient_labs_patient_id: Int
    lab__patient_labs_test_id: Int
    lab__patient_labs_specimen_date: String
    lab__patient_labs_lab_group_id: String
    lab__patient_labs_test_date: String
    lab__patient_labs_test_notes: String
    lab__patient_labs_status: String
    labtests_config_name: String
    regimen_drug_name: String
    regimen_drug_generic_name: String
    regimen_description: String
    regimen_weight: String
    regimen_form: String
    regimen_drug_id: Int
    regimen_quantity: Int
    regimen_request_time: String
    regimen_filled_time: String
    regimen_completed_time: String
    regimen_status: String
    regimen_prescribed_by: String
    regimen_note: String
    regimen_refill_off: String
    regimen_requested_by: String
    radiology_scan_name: String
    radiology_request_note: String
    radiology_request_date: String
    radiology_is_approved: Boolean
    radiology_approved_date: String
    radiology_status: Boolean
    radiology_cancelled: Boolean
    radio_cancel_date: String
    patient_diagnoses_date_of_entry: String
    patient_diagnoses_diag_type: String
    patient_diagnoses_active: Boolean
    patient_diagnoses_severity: String
    patient_diagnoses_diagnosisNote: String
    patient_diagnoses_diagnosis: String
    patient_diagnoses_status: String
    diagnoses_id: Int
    diagnoses_code: String
    diagnoses_type: String
    diagnoses_case: String
    diagnoses_parent_id: String
    diagnoses_oi: Int
    procedure_id: Int
    procedure_name: String
    procedure_icd_code: String
    procedure_description: String
    patient_procedure_id: Int
    patient_procedure_request_note: String
    patient_procedure_closing_text: String
    scheduled_on: String
    scheduled_by: String
    patient_procedure_time_started: String
    patient_procedure_time_start: String
    patient_procedure_time_stop: String
    patient_procedure_requested_by: String
    patient_procedure_note: String
    patient_procedure_note_time: String
    patient_procedure_note_type: String
    patient_procedure_request_date: String
    patient_procedure_status: String
    consultation_date_of_entry: String
    consultation_diagnoses: String
    consultation_note_type: String
    consultation_reason: String
    consultation_doctors_name: String
    patient_procedure_nursing_task_id: String
    patient_procedure_nursing_service: String
    vital_sign_type: String
    vital_sign_value: String
    vital_sign_unit: String
    vital_sign_min_val: String
    vital_sign_read_date: String
  }

  input NisaCollectionMutationInput {
    emr_id: Int
    emr_id_INC: Int
    emr_id_DEC: Int
    patient_first_name: String
    patient_last_name: String
    patient_middle_name: String
    patient_legacy_number: String
    date_of_birth: String
    phone_number: String
    sex: String
    patient_title: String
    provider_or_scheme: String
    patient_email: String
    patient_nationality: Int
    patient_nationality_INC: Int
    patient_nationality_DEC: Int
    patient_occupation: String
    patient_work_address: String
    patient_address: String
    patient_is_deceased: Boolean
    patient_is_active: Boolean
    record_date: String
    report_type: String
    encounter_id: Int
    encounter_id_INC: Int
    encounter_id_DEC: Int
    service_center: String
    hospital_id: Int
    hospital_id_INC: Int
    hospital_id_DEC: Int
    referral_id: String
    theatre_id: String
    surgeon_id: String
    bodypart_id: String
    anesthesiologist_id: String
    lab_template_data_label: String
    lab_result_data_value: String
    lab_template_data_lab_method_id: Int
    lab_template_data_lab_method_id_INC: Int
    lab_template_data_lab_method_id_DEC: Int
    lab_template_data_reference: String
    lab_template_data_lab_template_id: Int
    lab_template_data_lab_template_id_INC: Int
    lab_template_data_lab_template_id_DEC: Int
    lab_result_id: Int
    lab_result_id_INC: Int
    lab_result_id_DEC: Int
    lab_template_id: Int
    lab_template_id_INC: Int
    lab_template_id_DEC: Int
    lab_result_patient_lab_id: Int
    lab_result_patient_lab_id_INC: Int
    lab_result_patient_lab_id_DEC: Int
    lab_result_approved: Boolean
    lab_result_abnormal_lab_value: Int
    lab_result_abnormal_lab_value_INC: Int
    lab_result_abnormal_lab_value_DEC: Int
    lab_result_approved_by: String
    lab_result_approved_date: String
    lab__patient_labs_patient_id: Int
    lab__patient_labs_patient_id_INC: Int
    lab__patient_labs_patient_id_DEC: Int
    lab__patient_labs_test_id: Int
    lab__patient_labs_test_id_INC: Int
    lab__patient_labs_test_id_DEC: Int
    lab__patient_labs_specimen_date: String
    lab__patient_labs_lab_group_id: String
    lab__patient_labs_test_date: String
    lab__patient_labs_test_notes: String
    lab__patient_labs_status: String
    labtests_config_name: String
    regimen_drug_name: String
    regimen_drug_generic_name: String
    regimen_description: String
    regimen_weight: String
    regimen_form: String
    regimen_drug_id: Int
    regimen_drug_id_INC: Int
    regimen_drug_id_DEC: Int
    regimen_quantity: Int
    regimen_quantity_INC: Int
    regimen_quantity_DEC: Int
    regimen_request_time: String
    regimen_filled_time: String
    regimen_completed_time: String
    regimen_status: String
    regimen_prescribed_by: String
    regimen_note: String
    regimen_refill_off: String
    regimen_requested_by: String
    radiology_scan_name: String
    radiology_request_note: String
    radiology_request_date: String
    radiology_is_approved: Boolean
    radiology_approved_date: String
    radiology_status: Boolean
    radiology_cancelled: Boolean
    radio_cancel_date: String
    patient_diagnoses_date_of_entry: String
    patient_diagnoses_diag_type: String
    patient_diagnoses_active: Boolean
    patient_diagnoses_severity: String
    patient_diagnoses_diagnosisNote: String
    patient_diagnoses_diagnosis: String
    patient_diagnoses_status: String
    diagnoses_id: Int
    diagnoses_id_INC: Int
    diagnoses_id_DEC: Int
    diagnoses_code: String
    diagnoses_type: String
    diagnoses_case: String
    diagnoses_parent_id: String
    diagnoses_oi: Int
    diagnoses_oi_INC: Int
    diagnoses_oi_DEC: Int
    procedure_id: Int
    procedure_id_INC: Int
    procedure_id_DEC: Int
    procedure_name: String
    procedure_icd_code: String
    procedure_description: String
    patient_procedure_id: Int
    patient_procedure_id_INC: Int
    patient_procedure_id_DEC: Int
    patient_procedure_request_note: String
    patient_procedure_closing_text: String
    scheduled_on: String
    scheduled_by: String
    patient_procedure_time_started: String
    patient_procedure_time_start: String
    patient_procedure_time_stop: String
    patient_procedure_requested_by: String
    patient_procedure_note: String
    patient_procedure_note_time: String
    patient_procedure_note_type: String
    patient_procedure_request_date: String
    patient_procedure_status: String
    consultation_date_of_entry: String
    consultation_diagnoses: String
    consultation_note_type: String
    consultation_reason: String
    consultation_doctors_name: String
    patient_procedure_nursing_task_id: String
    patient_procedure_nursing_service: String
    vital_sign_type: String
    vital_sign_value: String
    vital_sign_unit: String
    vital_sign_min_val: String
    vital_sign_read_date: String
  }

  input NisaCollectionSort {
    _id: Int
    emr_id: Int
    patient_first_name: Int
    patient_last_name: Int
    patient_middle_name: Int
    patient_legacy_number: Int
    date_of_birth: Int
    phone_number: Int
    sex: Int
    patient_title: Int
    provider_or_scheme: Int
    patient_email: Int
    patient_nationality: Int
    patient_occupation: Int
    patient_work_address: Int
    patient_address: Int
    patient_is_deceased: Int
    patient_is_active: Int
    record_date: Int
    report_type: Int
    encounter_id: Int
    service_center: Int
    hospital_id: Int
    referral_id: Int
    theatre_id: Int
    surgeon_id: Int
    bodypart_id: Int
    anesthesiologist_id: Int
    lab_template_data_label: Int
    lab_result_data_value: Int
    lab_template_data_lab_method_id: Int
    lab_template_data_reference: Int
    lab_template_data_lab_template_id: Int
    lab_result_id: Int
    lab_template_id: Int
    lab_result_patient_lab_id: Int
    lab_result_approved: Int
    lab_result_abnormal_lab_value: Int
    lab_result_approved_by: Int
    lab_result_approved_date: Int
    lab__patient_labs_patient_id: Int
    lab__patient_labs_test_id: Int
    lab__patient_labs_specimen_date: Int
    lab__patient_labs_lab_group_id: Int
    lab__patient_labs_test_date: Int
    lab__patient_labs_test_notes: Int
    lab__patient_labs_status: Int
    labtests_config_name: Int
    regimen_drug_name: Int
    regimen_drug_generic_name: Int
    regimen_description: Int
    regimen_weight: Int
    regimen_form: Int
    regimen_drug_id: Int
    regimen_quantity: Int
    regimen_request_time: Int
    regimen_filled_time: Int
    regimen_completed_time: Int
    regimen_status: Int
    regimen_prescribed_by: Int
    regimen_note: Int
    regimen_refill_off: Int
    regimen_requested_by: Int
    radiology_scan_name: Int
    radiology_request_note: Int
    radiology_request_date: Int
    radiology_is_approved: Int
    radiology_approved_date: Int
    radiology_status: Int
    radiology_cancelled: Int
    radio_cancel_date: Int
    patient_diagnoses_date_of_entry: Int
    patient_diagnoses_diag_type: Int
    patient_diagnoses_active: Int
    patient_diagnoses_severity: Int
    patient_diagnoses_diagnosisNote: Int
    patient_diagnoses_diagnosis: Int
    patient_diagnoses_status: Int
    diagnoses_id: Int
    diagnoses_code: Int
    diagnoses_type: Int
    diagnoses_case: Int
    diagnoses_parent_id: Int
    diagnoses_oi: Int
    procedure_id: Int
    procedure_name: Int
    procedure_icd_code: Int
    procedure_description: Int
    patient_procedure_id: Int
    patient_procedure_request_note: Int
    patient_procedure_closing_text: Int
    scheduled_on: Int
    scheduled_by: Int
    patient_procedure_time_started: Int
    patient_procedure_time_start: Int
    patient_procedure_time_stop: Int
    patient_procedure_requested_by: Int
    patient_procedure_note: Int
    patient_procedure_note_time: Int
    patient_procedure_note_type: Int
    patient_procedure_request_date: Int
    patient_procedure_status: Int
    consultation_date_of_entry: Int
    consultation_diagnoses: Int
    consultation_note_type: Int
    consultation_reason: Int
    consultation_doctors_name: Int
    patient_procedure_nursing_task_id: Int
    patient_procedure_nursing_service: Int
    vital_sign_type: Int
    vital_sign_value: Int
    vital_sign_unit: Int
    vital_sign_min_val: Int
    vital_sign_read_date: Int
  }

  input NisaCollectionFilters {
    _id: String
    _id_ne: String
    _id_in: [String]
    emr_id_lt: Int
    emr_id_lte: Int
    emr_id_gt: Int
    emr_id_gte: Int
    emr_id: Int
    emr_id_ne: Int
    emr_id_in: [Int]
    patient_first_name_contains: String
    patient_first_name_startsWith: String
    patient_first_name_endsWith: String
    patient_first_name_regex: String
    patient_first_name: String
    patient_first_name_ne: String
    patient_first_name_in: [String]
    patient_last_name_contains: String
    patient_last_name_startsWith: String
    patient_last_name_endsWith: String
    patient_last_name_regex: String
    patient_last_name: String
    patient_last_name_ne: String
    patient_last_name_in: [String]
    patient_middle_name_contains: String
    patient_middle_name_startsWith: String
    patient_middle_name_endsWith: String
    patient_middle_name_regex: String
    patient_middle_name: String
    patient_middle_name_ne: String
    patient_middle_name_in: [String]
    patient_legacy_number_contains: String
    patient_legacy_number_startsWith: String
    patient_legacy_number_endsWith: String
    patient_legacy_number_regex: String
    patient_legacy_number: String
    patient_legacy_number_ne: String
    patient_legacy_number_in: [String]
    date_of_birth_contains: String
    date_of_birth_startsWith: String
    date_of_birth_endsWith: String
    date_of_birth_regex: String
    date_of_birth: String
    date_of_birth_ne: String
    date_of_birth_in: [String]
    phone_number_contains: String
    phone_number_startsWith: String
    phone_number_endsWith: String
    phone_number_regex: String
    phone_number: String
    phone_number_ne: String
    phone_number_in: [String]
    sex_contains: String
    sex_startsWith: String
    sex_endsWith: String
    sex_regex: String
    sex: String
    sex_ne: String
    sex_in: [String]
    patient_title_contains: String
    patient_title_startsWith: String
    patient_title_endsWith: String
    patient_title_regex: String
    patient_title: String
    patient_title_ne: String
    patient_title_in: [String]
    provider_or_scheme_contains: String
    provider_or_scheme_startsWith: String
    provider_or_scheme_endsWith: String
    provider_or_scheme_regex: String
    provider_or_scheme: String
    provider_or_scheme_ne: String
    provider_or_scheme_in: [String]
    patient_email_contains: String
    patient_email_startsWith: String
    patient_email_endsWith: String
    patient_email_regex: String
    patient_email: String
    patient_email_ne: String
    patient_email_in: [String]
    patient_nationality_lt: Int
    patient_nationality_lte: Int
    patient_nationality_gt: Int
    patient_nationality_gte: Int
    patient_nationality: Int
    patient_nationality_ne: Int
    patient_nationality_in: [Int]
    patient_occupation_contains: String
    patient_occupation_startsWith: String
    patient_occupation_endsWith: String
    patient_occupation_regex: String
    patient_occupation: String
    patient_occupation_ne: String
    patient_occupation_in: [String]
    patient_work_address_contains: String
    patient_work_address_startsWith: String
    patient_work_address_endsWith: String
    patient_work_address_regex: String
    patient_work_address: String
    patient_work_address_ne: String
    patient_work_address_in: [String]
    patient_address_contains: String
    patient_address_startsWith: String
    patient_address_endsWith: String
    patient_address_regex: String
    patient_address: String
    patient_address_ne: String
    patient_address_in: [String]
    patient_is_deceased: Boolean
    patient_is_deceased: Boolean
    patient_is_deceased_ne: Boolean
    patient_is_deceased_in: [Boolean]
    patient_is_active: Boolean
    patient_is_active: Boolean
    patient_is_active_ne: Boolean
    patient_is_active_in: [Boolean]
    record_date_lt: String
    record_date_lte: String
    record_date_gt: String
    record_date_gte: String
    record_date: String
    record_date_ne: String
    record_date_in: [String]
    report_type_contains: String
    report_type_startsWith: String
    report_type_endsWith: String
    report_type_regex: String
    report_type: String
    report_type_ne: String
    report_type_in: [String]
    encounter_id_lt: Int
    encounter_id_lte: Int
    encounter_id_gt: Int
    encounter_id_gte: Int
    encounter_id: Int
    encounter_id_ne: Int
    encounter_id_in: [Int]
    service_center_contains: String
    service_center_startsWith: String
    service_center_endsWith: String
    service_center_regex: String
    service_center: String
    service_center_ne: String
    service_center_in: [String]
    hospital_id_lt: Int
    hospital_id_lte: Int
    hospital_id_gt: Int
    hospital_id_gte: Int
    hospital_id: Int
    hospital_id_ne: Int
    hospital_id_in: [Int]
    referral_id_contains: String
    referral_id_startsWith: String
    referral_id_endsWith: String
    referral_id_regex: String
    referral_id: String
    referral_id_ne: String
    referral_id_in: [String]
    theatre_id_contains: String
    theatre_id_startsWith: String
    theatre_id_endsWith: String
    theatre_id_regex: String
    theatre_id: String
    theatre_id_ne: String
    theatre_id_in: [String]
    surgeon_id_contains: String
    surgeon_id_startsWith: String
    surgeon_id_endsWith: String
    surgeon_id_regex: String
    surgeon_id: String
    surgeon_id_ne: String
    surgeon_id_in: [String]
    bodypart_id_contains: String
    bodypart_id_startsWith: String
    bodypart_id_endsWith: String
    bodypart_id_regex: String
    bodypart_id: String
    bodypart_id_ne: String
    bodypart_id_in: [String]
    anesthesiologist_id_contains: String
    anesthesiologist_id_startsWith: String
    anesthesiologist_id_endsWith: String
    anesthesiologist_id_regex: String
    anesthesiologist_id: String
    anesthesiologist_id_ne: String
    anesthesiologist_id_in: [String]
    lab_template_data_label_contains: String
    lab_template_data_label_startsWith: String
    lab_template_data_label_endsWith: String
    lab_template_data_label_regex: String
    lab_template_data_label: String
    lab_template_data_label_ne: String
    lab_template_data_label_in: [String]
    lab_result_data_value_contains: String
    lab_result_data_value_startsWith: String
    lab_result_data_value_endsWith: String
    lab_result_data_value_regex: String
    lab_result_data_value: String
    lab_result_data_value_ne: String
    lab_result_data_value_in: [String]
    lab_template_data_lab_method_id_lt: Int
    lab_template_data_lab_method_id_lte: Int
    lab_template_data_lab_method_id_gt: Int
    lab_template_data_lab_method_id_gte: Int
    lab_template_data_lab_method_id: Int
    lab_template_data_lab_method_id_ne: Int
    lab_template_data_lab_method_id_in: [Int]
    lab_template_data_reference_contains: String
    lab_template_data_reference_startsWith: String
    lab_template_data_reference_endsWith: String
    lab_template_data_reference_regex: String
    lab_template_data_reference: String
    lab_template_data_reference_ne: String
    lab_template_data_reference_in: [String]
    lab_template_data_lab_template_id_lt: Int
    lab_template_data_lab_template_id_lte: Int
    lab_template_data_lab_template_id_gt: Int
    lab_template_data_lab_template_id_gte: Int
    lab_template_data_lab_template_id: Int
    lab_template_data_lab_template_id_ne: Int
    lab_template_data_lab_template_id_in: [Int]
    lab_result_id_lt: Int
    lab_result_id_lte: Int
    lab_result_id_gt: Int
    lab_result_id_gte: Int
    lab_result_id: Int
    lab_result_id_ne: Int
    lab_result_id_in: [Int]
    lab_template_id_lt: Int
    lab_template_id_lte: Int
    lab_template_id_gt: Int
    lab_template_id_gte: Int
    lab_template_id: Int
    lab_template_id_ne: Int
    lab_template_id_in: [Int]
    lab_result_patient_lab_id_lt: Int
    lab_result_patient_lab_id_lte: Int
    lab_result_patient_lab_id_gt: Int
    lab_result_patient_lab_id_gte: Int
    lab_result_patient_lab_id: Int
    lab_result_patient_lab_id_ne: Int
    lab_result_patient_lab_id_in: [Int]
    lab_result_approved: Boolean
    lab_result_approved: Boolean
    lab_result_approved_ne: Boolean
    lab_result_approved_in: [Boolean]
    lab_result_abnormal_lab_value_lt: Int
    lab_result_abnormal_lab_value_lte: Int
    lab_result_abnormal_lab_value_gt: Int
    lab_result_abnormal_lab_value_gte: Int
    lab_result_abnormal_lab_value: Int
    lab_result_abnormal_lab_value_ne: Int
    lab_result_abnormal_lab_value_in: [Int]
    lab_result_approved_by_contains: String
    lab_result_approved_by_startsWith: String
    lab_result_approved_by_endsWith: String
    lab_result_approved_by_regex: String
    lab_result_approved_by: String
    lab_result_approved_by_ne: String
    lab_result_approved_by_in: [String]
    lab_result_approved_date_contains: String
    lab_result_approved_date_startsWith: String
    lab_result_approved_date_endsWith: String
    lab_result_approved_date_regex: String
    lab_result_approved_date: String
    lab_result_approved_date_ne: String
    lab_result_approved_date_in: [String]
    lab__patient_labs_patient_id_lt: Int
    lab__patient_labs_patient_id_lte: Int
    lab__patient_labs_patient_id_gt: Int
    lab__patient_labs_patient_id_gte: Int
    lab__patient_labs_patient_id: Int
    lab__patient_labs_patient_id_ne: Int
    lab__patient_labs_patient_id_in: [Int]
    lab__patient_labs_test_id_lt: Int
    lab__patient_labs_test_id_lte: Int
    lab__patient_labs_test_id_gt: Int
    lab__patient_labs_test_id_gte: Int
    lab__patient_labs_test_id: Int
    lab__patient_labs_test_id_ne: Int
    lab__patient_labs_test_id_in: [Int]
    lab__patient_labs_specimen_date_contains: String
    lab__patient_labs_specimen_date_startsWith: String
    lab__patient_labs_specimen_date_endsWith: String
    lab__patient_labs_specimen_date_regex: String
    lab__patient_labs_specimen_date: String
    lab__patient_labs_specimen_date_ne: String
    lab__patient_labs_specimen_date_in: [String]
    lab__patient_labs_lab_group_id_contains: String
    lab__patient_labs_lab_group_id_startsWith: String
    lab__patient_labs_lab_group_id_endsWith: String
    lab__patient_labs_lab_group_id_regex: String
    lab__patient_labs_lab_group_id: String
    lab__patient_labs_lab_group_id_ne: String
    lab__patient_labs_lab_group_id_in: [String]
    lab__patient_labs_test_date_contains: String
    lab__patient_labs_test_date_startsWith: String
    lab__patient_labs_test_date_endsWith: String
    lab__patient_labs_test_date_regex: String
    lab__patient_labs_test_date: String
    lab__patient_labs_test_date_ne: String
    lab__patient_labs_test_date_in: [String]
    lab__patient_labs_test_notes_contains: String
    lab__patient_labs_test_notes_startsWith: String
    lab__patient_labs_test_notes_endsWith: String
    lab__patient_labs_test_notes_regex: String
    lab__patient_labs_test_notes: String
    lab__patient_labs_test_notes_ne: String
    lab__patient_labs_test_notes_in: [String]
    lab__patient_labs_status_contains: String
    lab__patient_labs_status_startsWith: String
    lab__patient_labs_status_endsWith: String
    lab__patient_labs_status_regex: String
    lab__patient_labs_status: String
    lab__patient_labs_status_ne: String
    lab__patient_labs_status_in: [String]
    labtests_config_name_contains: String
    labtests_config_name_startsWith: String
    labtests_config_name_endsWith: String
    labtests_config_name_regex: String
    labtests_config_name: String
    labtests_config_name_ne: String
    labtests_config_name_in: [String]
    regimen_drug_name_contains: String
    regimen_drug_name_startsWith: String
    regimen_drug_name_endsWith: String
    regimen_drug_name_regex: String
    regimen_drug_name: String
    regimen_drug_name_ne: String
    regimen_drug_name_in: [String]
    regimen_drug_generic_name_contains: String
    regimen_drug_generic_name_startsWith: String
    regimen_drug_generic_name_endsWith: String
    regimen_drug_generic_name_regex: String
    regimen_drug_generic_name: String
    regimen_drug_generic_name_ne: String
    regimen_drug_generic_name_in: [String]
    regimen_description_contains: String
    regimen_description_startsWith: String
    regimen_description_endsWith: String
    regimen_description_regex: String
    regimen_description: String
    regimen_description_ne: String
    regimen_description_in: [String]
    regimen_weight_contains: String
    regimen_weight_startsWith: String
    regimen_weight_endsWith: String
    regimen_weight_regex: String
    regimen_weight: String
    regimen_weight_ne: String
    regimen_weight_in: [String]
    regimen_form_contains: String
    regimen_form_startsWith: String
    regimen_form_endsWith: String
    regimen_form_regex: String
    regimen_form: String
    regimen_form_ne: String
    regimen_form_in: [String]
    regimen_drug_id_lt: Int
    regimen_drug_id_lte: Int
    regimen_drug_id_gt: Int
    regimen_drug_id_gte: Int
    regimen_drug_id: Int
    regimen_drug_id_ne: Int
    regimen_drug_id_in: [Int]
    regimen_quantity_lt: Int
    regimen_quantity_lte: Int
    regimen_quantity_gt: Int
    regimen_quantity_gte: Int
    regimen_quantity: Int
    regimen_quantity_ne: Int
    regimen_quantity_in: [Int]
    regimen_request_time_contains: String
    regimen_request_time_startsWith: String
    regimen_request_time_endsWith: String
    regimen_request_time_regex: String
    regimen_request_time: String
    regimen_request_time_ne: String
    regimen_request_time_in: [String]
    regimen_filled_time_contains: String
    regimen_filled_time_startsWith: String
    regimen_filled_time_endsWith: String
    regimen_filled_time_regex: String
    regimen_filled_time: String
    regimen_filled_time_ne: String
    regimen_filled_time_in: [String]
    regimen_completed_time_contains: String
    regimen_completed_time_startsWith: String
    regimen_completed_time_endsWith: String
    regimen_completed_time_regex: String
    regimen_completed_time: String
    regimen_completed_time_ne: String
    regimen_completed_time_in: [String]
    regimen_status_contains: String
    regimen_status_startsWith: String
    regimen_status_endsWith: String
    regimen_status_regex: String
    regimen_status: String
    regimen_status_ne: String
    regimen_status_in: [String]
    regimen_prescribed_by_contains: String
    regimen_prescribed_by_startsWith: String
    regimen_prescribed_by_endsWith: String
    regimen_prescribed_by_regex: String
    regimen_prescribed_by: String
    regimen_prescribed_by_ne: String
    regimen_prescribed_by_in: [String]
    regimen_note_contains: String
    regimen_note_startsWith: String
    regimen_note_endsWith: String
    regimen_note_regex: String
    regimen_note: String
    regimen_note_ne: String
    regimen_note_in: [String]
    regimen_refill_off_contains: String
    regimen_refill_off_startsWith: String
    regimen_refill_off_endsWith: String
    regimen_refill_off_regex: String
    regimen_refill_off: String
    regimen_refill_off_ne: String
    regimen_refill_off_in: [String]
    regimen_requested_by_contains: String
    regimen_requested_by_startsWith: String
    regimen_requested_by_endsWith: String
    regimen_requested_by_regex: String
    regimen_requested_by: String
    regimen_requested_by_ne: String
    regimen_requested_by_in: [String]
    radiology_scan_name_contains: String
    radiology_scan_name_startsWith: String
    radiology_scan_name_endsWith: String
    radiology_scan_name_regex: String
    radiology_scan_name: String
    radiology_scan_name_ne: String
    radiology_scan_name_in: [String]
    radiology_request_note_contains: String
    radiology_request_note_startsWith: String
    radiology_request_note_endsWith: String
    radiology_request_note_regex: String
    radiology_request_note: String
    radiology_request_note_ne: String
    radiology_request_note_in: [String]
    radiology_request_date_contains: String
    radiology_request_date_startsWith: String
    radiology_request_date_endsWith: String
    radiology_request_date_regex: String
    radiology_request_date: String
    radiology_request_date_ne: String
    radiology_request_date_in: [String]
    radiology_is_approved: Boolean
    radiology_is_approved: Boolean
    radiology_is_approved_ne: Boolean
    radiology_is_approved_in: [Boolean]
    radiology_approved_date_contains: String
    radiology_approved_date_startsWith: String
    radiology_approved_date_endsWith: String
    radiology_approved_date_regex: String
    radiology_approved_date: String
    radiology_approved_date_ne: String
    radiology_approved_date_in: [String]
    radiology_status: Boolean
    radiology_status: Boolean
    radiology_status_ne: Boolean
    radiology_status_in: [Boolean]
    radiology_cancelled: Boolean
    radiology_cancelled: Boolean
    radiology_cancelled_ne: Boolean
    radiology_cancelled_in: [Boolean]
    radio_cancel_date_contains: String
    radio_cancel_date_startsWith: String
    radio_cancel_date_endsWith: String
    radio_cancel_date_regex: String
    radio_cancel_date: String
    radio_cancel_date_ne: String
    radio_cancel_date_in: [String]
    patient_diagnoses_date_of_entry_contains: String
    patient_diagnoses_date_of_entry_startsWith: String
    patient_diagnoses_date_of_entry_endsWith: String
    patient_diagnoses_date_of_entry_regex: String
    patient_diagnoses_date_of_entry: String
    patient_diagnoses_date_of_entry_ne: String
    patient_diagnoses_date_of_entry_in: [String]
    patient_diagnoses_diag_type_contains: String
    patient_diagnoses_diag_type_startsWith: String
    patient_diagnoses_diag_type_endsWith: String
    patient_diagnoses_diag_type_regex: String
    patient_diagnoses_diag_type: String
    patient_diagnoses_diag_type_ne: String
    patient_diagnoses_diag_type_in: [String]
    patient_diagnoses_active: Boolean
    patient_diagnoses_active: Boolean
    patient_diagnoses_active_ne: Boolean
    patient_diagnoses_active_in: [Boolean]
    patient_diagnoses_severity_contains: String
    patient_diagnoses_severity_startsWith: String
    patient_diagnoses_severity_endsWith: String
    patient_diagnoses_severity_regex: String
    patient_diagnoses_severity: String
    patient_diagnoses_severity_ne: String
    patient_diagnoses_severity_in: [String]
    patient_diagnoses_diagnosisNote_contains: String
    patient_diagnoses_diagnosisNote_startsWith: String
    patient_diagnoses_diagnosisNote_endsWith: String
    patient_diagnoses_diagnosisNote_regex: String
    patient_diagnoses_diagnosisNote: String
    patient_diagnoses_diagnosisNote_ne: String
    patient_diagnoses_diagnosisNote_in: [String]
    patient_diagnoses_diagnosis_contains: String
    patient_diagnoses_diagnosis_startsWith: String
    patient_diagnoses_diagnosis_endsWith: String
    patient_diagnoses_diagnosis_regex: String
    patient_diagnoses_diagnosis: String
    patient_diagnoses_diagnosis_ne: String
    patient_diagnoses_diagnosis_in: [String]
    patient_diagnoses_status_contains: String
    patient_diagnoses_status_startsWith: String
    patient_diagnoses_status_endsWith: String
    patient_diagnoses_status_regex: String
    patient_diagnoses_status: String
    patient_diagnoses_status_ne: String
    patient_diagnoses_status_in: [String]
    diagnoses_id_lt: Int
    diagnoses_id_lte: Int
    diagnoses_id_gt: Int
    diagnoses_id_gte: Int
    diagnoses_id: Int
    diagnoses_id_ne: Int
    diagnoses_id_in: [Int]
    diagnoses_code_contains: String
    diagnoses_code_startsWith: String
    diagnoses_code_endsWith: String
    diagnoses_code_regex: String
    diagnoses_code: String
    diagnoses_code_ne: String
    diagnoses_code_in: [String]
    diagnoses_type_contains: String
    diagnoses_type_startsWith: String
    diagnoses_type_endsWith: String
    diagnoses_type_regex: String
    diagnoses_type: String
    diagnoses_type_ne: String
    diagnoses_type_in: [String]
    diagnoses_case_contains: String
    diagnoses_case_startsWith: String
    diagnoses_case_endsWith: String
    diagnoses_case_regex: String
    diagnoses_case: String
    diagnoses_case_ne: String
    diagnoses_case_in: [String]
    diagnoses_parent_id_contains: String
    diagnoses_parent_id_startsWith: String
    diagnoses_parent_id_endsWith: String
    diagnoses_parent_id_regex: String
    diagnoses_parent_id: String
    diagnoses_parent_id_ne: String
    diagnoses_parent_id_in: [String]
    diagnoses_oi_lt: Int
    diagnoses_oi_lte: Int
    diagnoses_oi_gt: Int
    diagnoses_oi_gte: Int
    diagnoses_oi: Int
    diagnoses_oi_ne: Int
    diagnoses_oi_in: [Int]
    procedure_id_lt: Int
    procedure_id_lte: Int
    procedure_id_gt: Int
    procedure_id_gte: Int
    procedure_id: Int
    procedure_id_ne: Int
    procedure_id_in: [Int]
    procedure_name_contains: String
    procedure_name_startsWith: String
    procedure_name_endsWith: String
    procedure_name_regex: String
    procedure_name: String
    procedure_name_ne: String
    procedure_name_in: [String]
    procedure_icd_code_contains: String
    procedure_icd_code_startsWith: String
    procedure_icd_code_endsWith: String
    procedure_icd_code_regex: String
    procedure_icd_code: String
    procedure_icd_code_ne: String
    procedure_icd_code_in: [String]
    procedure_description_contains: String
    procedure_description_startsWith: String
    procedure_description_endsWith: String
    procedure_description_regex: String
    procedure_description: String
    procedure_description_ne: String
    procedure_description_in: [String]
    patient_procedure_id_lt: Int
    patient_procedure_id_lte: Int
    patient_procedure_id_gt: Int
    patient_procedure_id_gte: Int
    patient_procedure_id: Int
    patient_procedure_id_ne: Int
    patient_procedure_id_in: [Int]
    patient_procedure_request_note_contains: String
    patient_procedure_request_note_startsWith: String
    patient_procedure_request_note_endsWith: String
    patient_procedure_request_note_regex: String
    patient_procedure_request_note: String
    patient_procedure_request_note_ne: String
    patient_procedure_request_note_in: [String]
    patient_procedure_closing_text_contains: String
    patient_procedure_closing_text_startsWith: String
    patient_procedure_closing_text_endsWith: String
    patient_procedure_closing_text_regex: String
    patient_procedure_closing_text: String
    patient_procedure_closing_text_ne: String
    patient_procedure_closing_text_in: [String]
    scheduled_on_contains: String
    scheduled_on_startsWith: String
    scheduled_on_endsWith: String
    scheduled_on_regex: String
    scheduled_on: String
    scheduled_on_ne: String
    scheduled_on_in: [String]
    scheduled_by_contains: String
    scheduled_by_startsWith: String
    scheduled_by_endsWith: String
    scheduled_by_regex: String
    scheduled_by: String
    scheduled_by_ne: String
    scheduled_by_in: [String]
    patient_procedure_time_started_contains: String
    patient_procedure_time_started_startsWith: String
    patient_procedure_time_started_endsWith: String
    patient_procedure_time_started_regex: String
    patient_procedure_time_started: String
    patient_procedure_time_started_ne: String
    patient_procedure_time_started_in: [String]
    patient_procedure_time_start_contains: String
    patient_procedure_time_start_startsWith: String
    patient_procedure_time_start_endsWith: String
    patient_procedure_time_start_regex: String
    patient_procedure_time_start: String
    patient_procedure_time_start_ne: String
    patient_procedure_time_start_in: [String]
    patient_procedure_time_stop_contains: String
    patient_procedure_time_stop_startsWith: String
    patient_procedure_time_stop_endsWith: String
    patient_procedure_time_stop_regex: String
    patient_procedure_time_stop: String
    patient_procedure_time_stop_ne: String
    patient_procedure_time_stop_in: [String]
    patient_procedure_requested_by_contains: String
    patient_procedure_requested_by_startsWith: String
    patient_procedure_requested_by_endsWith: String
    patient_procedure_requested_by_regex: String
    patient_procedure_requested_by: String
    patient_procedure_requested_by_ne: String
    patient_procedure_requested_by_in: [String]
    patient_procedure_note_contains: String
    patient_procedure_note_startsWith: String
    patient_procedure_note_endsWith: String
    patient_procedure_note_regex: String
    patient_procedure_note: String
    patient_procedure_note_ne: String
    patient_procedure_note_in: [String]
    patient_procedure_note_time_contains: String
    patient_procedure_note_time_startsWith: String
    patient_procedure_note_time_endsWith: String
    patient_procedure_note_time_regex: String
    patient_procedure_note_time: String
    patient_procedure_note_time_ne: String
    patient_procedure_note_time_in: [String]
    patient_procedure_note_type_contains: String
    patient_procedure_note_type_startsWith: String
    patient_procedure_note_type_endsWith: String
    patient_procedure_note_type_regex: String
    patient_procedure_note_type: String
    patient_procedure_note_type_ne: String
    patient_procedure_note_type_in: [String]
    patient_procedure_request_date_contains: String
    patient_procedure_request_date_startsWith: String
    patient_procedure_request_date_endsWith: String
    patient_procedure_request_date_regex: String
    patient_procedure_request_date: String
    patient_procedure_request_date_ne: String
    patient_procedure_request_date_in: [String]
    patient_procedure_status_contains: String
    patient_procedure_status_startsWith: String
    patient_procedure_status_endsWith: String
    patient_procedure_status_regex: String
    patient_procedure_status: String
    patient_procedure_status_ne: String
    patient_procedure_status_in: [String]
    consultation_date_of_entry_contains: String
    consultation_date_of_entry_startsWith: String
    consultation_date_of_entry_endsWith: String
    consultation_date_of_entry_regex: String
    consultation_date_of_entry: String
    consultation_date_of_entry_ne: String
    consultation_date_of_entry_in: [String]
    consultation_diagnoses_contains: String
    consultation_diagnoses_startsWith: String
    consultation_diagnoses_endsWith: String
    consultation_diagnoses_regex: String
    consultation_diagnoses: String
    consultation_diagnoses_ne: String
    consultation_diagnoses_in: [String]
    consultation_note_type_contains: String
    consultation_note_type_startsWith: String
    consultation_note_type_endsWith: String
    consultation_note_type_regex: String
    consultation_note_type: String
    consultation_note_type_ne: String
    consultation_note_type_in: [String]
    consultation_reason_contains: String
    consultation_reason_startsWith: String
    consultation_reason_endsWith: String
    consultation_reason_regex: String
    consultation_reason: String
    consultation_reason_ne: String
    consultation_reason_in: [String]
    consultation_doctors_name_contains: String
    consultation_doctors_name_startsWith: String
    consultation_doctors_name_endsWith: String
    consultation_doctors_name_regex: String
    consultation_doctors_name: String
    consultation_doctors_name_ne: String
    consultation_doctors_name_in: [String]
    patient_procedure_nursing_task_id_contains: String
    patient_procedure_nursing_task_id_startsWith: String
    patient_procedure_nursing_task_id_endsWith: String
    patient_procedure_nursing_task_id_regex: String
    patient_procedure_nursing_task_id: String
    patient_procedure_nursing_task_id_ne: String
    patient_procedure_nursing_task_id_in: [String]
    patient_procedure_nursing_service_contains: String
    patient_procedure_nursing_service_startsWith: String
    patient_procedure_nursing_service_endsWith: String
    patient_procedure_nursing_service_regex: String
    patient_procedure_nursing_service: String
    patient_procedure_nursing_service_ne: String
    patient_procedure_nursing_service_in: [String]
    vital_sign_type_contains: String
    vital_sign_type_startsWith: String
    vital_sign_type_endsWith: String
    vital_sign_type_regex: String
    vital_sign_type: String
    vital_sign_type_ne: String
    vital_sign_type_in: [String]
    vital_sign_value_contains: String
    vital_sign_value_startsWith: String
    vital_sign_value_endsWith: String
    vital_sign_value_regex: String
    vital_sign_value: String
    vital_sign_value_ne: String
    vital_sign_value_in: [String]
    vital_sign_unit_contains: String
    vital_sign_unit_startsWith: String
    vital_sign_unit_endsWith: String
    vital_sign_unit_regex: String
    vital_sign_unit: String
    vital_sign_unit_ne: String
    vital_sign_unit_in: [String]
    vital_sign_min_val_contains: String
    vital_sign_min_val_startsWith: String
    vital_sign_min_val_endsWith: String
    vital_sign_min_val_regex: String
    vital_sign_min_val: String
    vital_sign_min_val_ne: String
    vital_sign_min_val_in: [String]
    vital_sign_read_date_contains: String
    vital_sign_read_date_startsWith: String
    vital_sign_read_date_endsWith: String
    vital_sign_read_date_regex: String
    vital_sign_read_date: String
    vital_sign_read_date_ne: String
    vital_sign_read_date_in: [String]
    OR: [NisaCollectionFilters]
  }
  
`;
  
  
export const mutation = `

  createNisaCollection (
    NisaCollection: NisaCollectionInput
  ): NisaCollectionMutationResult

  updateNisaCollection (
    _id: String,
    Updates: NisaCollectionMutationInput
  ): NisaCollectionMutationResult

  updateNisaCollections (
    _ids: [String],
    Updates: NisaCollectionMutationInput
  ): NisaCollectionMutationResultMulti

  updateNisaCollectionsBulk (
    Match: NisaCollectionFilters,
    Updates: NisaCollectionMutationInput
  ): NisaCollectionBulkMutationResult

  deleteNisaCollection (
    _id: String
  ): Boolean

`;


export const query = `

  allNisaCollections (
    _id: String,
    _id_ne: String,
    _id_in: [String],
    emr_id_lt: Int,
    emr_id_lte: Int,
    emr_id_gt: Int,
    emr_id_gte: Int,
    emr_id: Int,
    emr_id_ne: Int,
    emr_id_in: [Int],
    patient_first_name_contains: String,
    patient_first_name_startsWith: String,
    patient_first_name_endsWith: String,
    patient_first_name_regex: String,
    patient_first_name: String,
    patient_first_name_ne: String,
    patient_first_name_in: [String],
    patient_last_name_contains: String,
    patient_last_name_startsWith: String,
    patient_last_name_endsWith: String,
    patient_last_name_regex: String,
    patient_last_name: String,
    patient_last_name_ne: String,
    patient_last_name_in: [String],
    patient_middle_name_contains: String,
    patient_middle_name_startsWith: String,
    patient_middle_name_endsWith: String,
    patient_middle_name_regex: String,
    patient_middle_name: String,
    patient_middle_name_ne: String,
    patient_middle_name_in: [String],
    patient_legacy_number_contains: String,
    patient_legacy_number_startsWith: String,
    patient_legacy_number_endsWith: String,
    patient_legacy_number_regex: String,
    patient_legacy_number: String,
    patient_legacy_number_ne: String,
    patient_legacy_number_in: [String],
    date_of_birth_contains: String,
    date_of_birth_startsWith: String,
    date_of_birth_endsWith: String,
    date_of_birth_regex: String,
    date_of_birth: String,
    date_of_birth_ne: String,
    date_of_birth_in: [String],
    phone_number_contains: String,
    phone_number_startsWith: String,
    phone_number_endsWith: String,
    phone_number_regex: String,
    phone_number: String,
    phone_number_ne: String,
    phone_number_in: [String],
    sex_contains: String,
    sex_startsWith: String,
    sex_endsWith: String,
    sex_regex: String,
    sex: String,
    sex_ne: String,
    sex_in: [String],
    patient_title_contains: String,
    patient_title_startsWith: String,
    patient_title_endsWith: String,
    patient_title_regex: String,
    patient_title: String,
    patient_title_ne: String,
    patient_title_in: [String],
    provider_or_scheme_contains: String,
    provider_or_scheme_startsWith: String,
    provider_or_scheme_endsWith: String,
    provider_or_scheme_regex: String,
    provider_or_scheme: String,
    provider_or_scheme_ne: String,
    provider_or_scheme_in: [String],
    patient_email_contains: String,
    patient_email_startsWith: String,
    patient_email_endsWith: String,
    patient_email_regex: String,
    patient_email: String,
    patient_email_ne: String,
    patient_email_in: [String],
    patient_nationality_lt: Int,
    patient_nationality_lte: Int,
    patient_nationality_gt: Int,
    patient_nationality_gte: Int,
    patient_nationality: Int,
    patient_nationality_ne: Int,
    patient_nationality_in: [Int],
    patient_occupation_contains: String,
    patient_occupation_startsWith: String,
    patient_occupation_endsWith: String,
    patient_occupation_regex: String,
    patient_occupation: String,
    patient_occupation_ne: String,
    patient_occupation_in: [String],
    patient_work_address_contains: String,
    patient_work_address_startsWith: String,
    patient_work_address_endsWith: String,
    patient_work_address_regex: String,
    patient_work_address: String,
    patient_work_address_ne: String,
    patient_work_address_in: [String],
    patient_address_contains: String,
    patient_address_startsWith: String,
    patient_address_endsWith: String,
    patient_address_regex: String,
    patient_address: String,
    patient_address_ne: String,
    patient_address_in: [String],
    patient_is_deceased: Boolean,
    patient_is_deceased: Boolean,
    patient_is_deceased_ne: Boolean,
    patient_is_deceased_in: [Boolean],
    patient_is_active: Boolean,
    patient_is_active: Boolean,
    patient_is_active_ne: Boolean,
    patient_is_active_in: [Boolean],
    record_date_lt: String,
    record_date_lte: String,
    record_date_gt: String,
    record_date_gte: String,
    record_date: String,
    record_date_ne: String,
    record_date_in: [String],
    report_type_contains: String,
    report_type_startsWith: String,
    report_type_endsWith: String,
    report_type_regex: String,
    report_type: String,
    report_type_ne: String,
    report_type_in: [String],
    encounter_id_lt: Int,
    encounter_id_lte: Int,
    encounter_id_gt: Int,
    encounter_id_gte: Int,
    encounter_id: Int,
    encounter_id_ne: Int,
    encounter_id_in: [Int],
    service_center_contains: String,
    service_center_startsWith: String,
    service_center_endsWith: String,
    service_center_regex: String,
    service_center: String,
    service_center_ne: String,
    service_center_in: [String],
    hospital_id_lt: Int,
    hospital_id_lte: Int,
    hospital_id_gt: Int,
    hospital_id_gte: Int,
    hospital_id: Int,
    hospital_id_ne: Int,
    hospital_id_in: [Int],
    referral_id_contains: String,
    referral_id_startsWith: String,
    referral_id_endsWith: String,
    referral_id_regex: String,
    referral_id: String,
    referral_id_ne: String,
    referral_id_in: [String],
    theatre_id_contains: String,
    theatre_id_startsWith: String,
    theatre_id_endsWith: String,
    theatre_id_regex: String,
    theatre_id: String,
    theatre_id_ne: String,
    theatre_id_in: [String],
    surgeon_id_contains: String,
    surgeon_id_startsWith: String,
    surgeon_id_endsWith: String,
    surgeon_id_regex: String,
    surgeon_id: String,
    surgeon_id_ne: String,
    surgeon_id_in: [String],
    bodypart_id_contains: String,
    bodypart_id_startsWith: String,
    bodypart_id_endsWith: String,
    bodypart_id_regex: String,
    bodypart_id: String,
    bodypart_id_ne: String,
    bodypart_id_in: [String],
    anesthesiologist_id_contains: String,
    anesthesiologist_id_startsWith: String,
    anesthesiologist_id_endsWith: String,
    anesthesiologist_id_regex: String,
    anesthesiologist_id: String,
    anesthesiologist_id_ne: String,
    anesthesiologist_id_in: [String],
    lab_template_data_label_contains: String,
    lab_template_data_label_startsWith: String,
    lab_template_data_label_endsWith: String,
    lab_template_data_label_regex: String,
    lab_template_data_label: String,
    lab_template_data_label_ne: String,
    lab_template_data_label_in: [String],
    lab_result_data_value_contains: String,
    lab_result_data_value_startsWith: String,
    lab_result_data_value_endsWith: String,
    lab_result_data_value_regex: String,
    lab_result_data_value: String,
    lab_result_data_value_ne: String,
    lab_result_data_value_in: [String],
    lab_template_data_lab_method_id_lt: Int,
    lab_template_data_lab_method_id_lte: Int,
    lab_template_data_lab_method_id_gt: Int,
    lab_template_data_lab_method_id_gte: Int,
    lab_template_data_lab_method_id: Int,
    lab_template_data_lab_method_id_ne: Int,
    lab_template_data_lab_method_id_in: [Int],
    lab_template_data_reference_contains: String,
    lab_template_data_reference_startsWith: String,
    lab_template_data_reference_endsWith: String,
    lab_template_data_reference_regex: String,
    lab_template_data_reference: String,
    lab_template_data_reference_ne: String,
    lab_template_data_reference_in: [String],
    lab_template_data_lab_template_id_lt: Int,
    lab_template_data_lab_template_id_lte: Int,
    lab_template_data_lab_template_id_gt: Int,
    lab_template_data_lab_template_id_gte: Int,
    lab_template_data_lab_template_id: Int,
    lab_template_data_lab_template_id_ne: Int,
    lab_template_data_lab_template_id_in: [Int],
    lab_result_id_lt: Int,
    lab_result_id_lte: Int,
    lab_result_id_gt: Int,
    lab_result_id_gte: Int,
    lab_result_id: Int,
    lab_result_id_ne: Int,
    lab_result_id_in: [Int],
    lab_template_id_lt: Int,
    lab_template_id_lte: Int,
    lab_template_id_gt: Int,
    lab_template_id_gte: Int,
    lab_template_id: Int,
    lab_template_id_ne: Int,
    lab_template_id_in: [Int],
    lab_result_patient_lab_id_lt: Int,
    lab_result_patient_lab_id_lte: Int,
    lab_result_patient_lab_id_gt: Int,
    lab_result_patient_lab_id_gte: Int,
    lab_result_patient_lab_id: Int,
    lab_result_patient_lab_id_ne: Int,
    lab_result_patient_lab_id_in: [Int],
    lab_result_approved: Boolean,
    lab_result_approved: Boolean,
    lab_result_approved_ne: Boolean,
    lab_result_approved_in: [Boolean],
    lab_result_abnormal_lab_value_lt: Int,
    lab_result_abnormal_lab_value_lte: Int,
    lab_result_abnormal_lab_value_gt: Int,
    lab_result_abnormal_lab_value_gte: Int,
    lab_result_abnormal_lab_value: Int,
    lab_result_abnormal_lab_value_ne: Int,
    lab_result_abnormal_lab_value_in: [Int],
    lab_result_approved_by_contains: String,
    lab_result_approved_by_startsWith: String,
    lab_result_approved_by_endsWith: String,
    lab_result_approved_by_regex: String,
    lab_result_approved_by: String,
    lab_result_approved_by_ne: String,
    lab_result_approved_by_in: [String],
    lab_result_approved_date_contains: String,
    lab_result_approved_date_startsWith: String,
    lab_result_approved_date_endsWith: String,
    lab_result_approved_date_regex: String,
    lab_result_approved_date: String,
    lab_result_approved_date_ne: String,
    lab_result_approved_date_in: [String],
    lab__patient_labs_patient_id_lt: Int,
    lab__patient_labs_patient_id_lte: Int,
    lab__patient_labs_patient_id_gt: Int,
    lab__patient_labs_patient_id_gte: Int,
    lab__patient_labs_patient_id: Int,
    lab__patient_labs_patient_id_ne: Int,
    lab__patient_labs_patient_id_in: [Int],
    lab__patient_labs_test_id_lt: Int,
    lab__patient_labs_test_id_lte: Int,
    lab__patient_labs_test_id_gt: Int,
    lab__patient_labs_test_id_gte: Int,
    lab__patient_labs_test_id: Int,
    lab__patient_labs_test_id_ne: Int,
    lab__patient_labs_test_id_in: [Int],
    lab__patient_labs_specimen_date_contains: String,
    lab__patient_labs_specimen_date_startsWith: String,
    lab__patient_labs_specimen_date_endsWith: String,
    lab__patient_labs_specimen_date_regex: String,
    lab__patient_labs_specimen_date: String,
    lab__patient_labs_specimen_date_ne: String,
    lab__patient_labs_specimen_date_in: [String],
    lab__patient_labs_lab_group_id_contains: String,
    lab__patient_labs_lab_group_id_startsWith: String,
    lab__patient_labs_lab_group_id_endsWith: String,
    lab__patient_labs_lab_group_id_regex: String,
    lab__patient_labs_lab_group_id: String,
    lab__patient_labs_lab_group_id_ne: String,
    lab__patient_labs_lab_group_id_in: [String],
    lab__patient_labs_test_date_contains: String,
    lab__patient_labs_test_date_startsWith: String,
    lab__patient_labs_test_date_endsWith: String,
    lab__patient_labs_test_date_regex: String,
    lab__patient_labs_test_date: String,
    lab__patient_labs_test_date_ne: String,
    lab__patient_labs_test_date_in: [String],
    lab__patient_labs_test_notes_contains: String,
    lab__patient_labs_test_notes_startsWith: String,
    lab__patient_labs_test_notes_endsWith: String,
    lab__patient_labs_test_notes_regex: String,
    lab__patient_labs_test_notes: String,
    lab__patient_labs_test_notes_ne: String,
    lab__patient_labs_test_notes_in: [String],
    lab__patient_labs_status_contains: String,
    lab__patient_labs_status_startsWith: String,
    lab__patient_labs_status_endsWith: String,
    lab__patient_labs_status_regex: String,
    lab__patient_labs_status: String,
    lab__patient_labs_status_ne: String,
    lab__patient_labs_status_in: [String],
    labtests_config_name_contains: String,
    labtests_config_name_startsWith: String,
    labtests_config_name_endsWith: String,
    labtests_config_name_regex: String,
    labtests_config_name: String,
    labtests_config_name_ne: String,
    labtests_config_name_in: [String],
    regimen_drug_name_contains: String,
    regimen_drug_name_startsWith: String,
    regimen_drug_name_endsWith: String,
    regimen_drug_name_regex: String,
    regimen_drug_name: String,
    regimen_drug_name_ne: String,
    regimen_drug_name_in: [String],
    regimen_drug_generic_name_contains: String,
    regimen_drug_generic_name_startsWith: String,
    regimen_drug_generic_name_endsWith: String,
    regimen_drug_generic_name_regex: String,
    regimen_drug_generic_name: String,
    regimen_drug_generic_name_ne: String,
    regimen_drug_generic_name_in: [String],
    regimen_description_contains: String,
    regimen_description_startsWith: String,
    regimen_description_endsWith: String,
    regimen_description_regex: String,
    regimen_description: String,
    regimen_description_ne: String,
    regimen_description_in: [String],
    regimen_weight_contains: String,
    regimen_weight_startsWith: String,
    regimen_weight_endsWith: String,
    regimen_weight_regex: String,
    regimen_weight: String,
    regimen_weight_ne: String,
    regimen_weight_in: [String],
    regimen_form_contains: String,
    regimen_form_startsWith: String,
    regimen_form_endsWith: String,
    regimen_form_regex: String,
    regimen_form: String,
    regimen_form_ne: String,
    regimen_form_in: [String],
    regimen_drug_id_lt: Int,
    regimen_drug_id_lte: Int,
    regimen_drug_id_gt: Int,
    regimen_drug_id_gte: Int,
    regimen_drug_id: Int,
    regimen_drug_id_ne: Int,
    regimen_drug_id_in: [Int],
    regimen_quantity_lt: Int,
    regimen_quantity_lte: Int,
    regimen_quantity_gt: Int,
    regimen_quantity_gte: Int,
    regimen_quantity: Int,
    regimen_quantity_ne: Int,
    regimen_quantity_in: [Int],
    regimen_request_time_contains: String,
    regimen_request_time_startsWith: String,
    regimen_request_time_endsWith: String,
    regimen_request_time_regex: String,
    regimen_request_time: String,
    regimen_request_time_ne: String,
    regimen_request_time_in: [String],
    regimen_filled_time_contains: String,
    regimen_filled_time_startsWith: String,
    regimen_filled_time_endsWith: String,
    regimen_filled_time_regex: String,
    regimen_filled_time: String,
    regimen_filled_time_ne: String,
    regimen_filled_time_in: [String],
    regimen_completed_time_contains: String,
    regimen_completed_time_startsWith: String,
    regimen_completed_time_endsWith: String,
    regimen_completed_time_regex: String,
    regimen_completed_time: String,
    regimen_completed_time_ne: String,
    regimen_completed_time_in: [String],
    regimen_status_contains: String,
    regimen_status_startsWith: String,
    regimen_status_endsWith: String,
    regimen_status_regex: String,
    regimen_status: String,
    regimen_status_ne: String,
    regimen_status_in: [String],
    regimen_prescribed_by_contains: String,
    regimen_prescribed_by_startsWith: String,
    regimen_prescribed_by_endsWith: String,
    regimen_prescribed_by_regex: String,
    regimen_prescribed_by: String,
    regimen_prescribed_by_ne: String,
    regimen_prescribed_by_in: [String],
    regimen_note_contains: String,
    regimen_note_startsWith: String,
    regimen_note_endsWith: String,
    regimen_note_regex: String,
    regimen_note: String,
    regimen_note_ne: String,
    regimen_note_in: [String],
    regimen_refill_off_contains: String,
    regimen_refill_off_startsWith: String,
    regimen_refill_off_endsWith: String,
    regimen_refill_off_regex: String,
    regimen_refill_off: String,
    regimen_refill_off_ne: String,
    regimen_refill_off_in: [String],
    regimen_requested_by_contains: String,
    regimen_requested_by_startsWith: String,
    regimen_requested_by_endsWith: String,
    regimen_requested_by_regex: String,
    regimen_requested_by: String,
    regimen_requested_by_ne: String,
    regimen_requested_by_in: [String],
    radiology_scan_name_contains: String,
    radiology_scan_name_startsWith: String,
    radiology_scan_name_endsWith: String,
    radiology_scan_name_regex: String,
    radiology_scan_name: String,
    radiology_scan_name_ne: String,
    radiology_scan_name_in: [String],
    radiology_request_note_contains: String,
    radiology_request_note_startsWith: String,
    radiology_request_note_endsWith: String,
    radiology_request_note_regex: String,
    radiology_request_note: String,
    radiology_request_note_ne: String,
    radiology_request_note_in: [String],
    radiology_request_date_contains: String,
    radiology_request_date_startsWith: String,
    radiology_request_date_endsWith: String,
    radiology_request_date_regex: String,
    radiology_request_date: String,
    radiology_request_date_ne: String,
    radiology_request_date_in: [String],
    radiology_is_approved: Boolean,
    radiology_is_approved: Boolean,
    radiology_is_approved_ne: Boolean,
    radiology_is_approved_in: [Boolean],
    radiology_approved_date_contains: String,
    radiology_approved_date_startsWith: String,
    radiology_approved_date_endsWith: String,
    radiology_approved_date_regex: String,
    radiology_approved_date: String,
    radiology_approved_date_ne: String,
    radiology_approved_date_in: [String],
    radiology_status: Boolean,
    radiology_status: Boolean,
    radiology_status_ne: Boolean,
    radiology_status_in: [Boolean],
    radiology_cancelled: Boolean,
    radiology_cancelled: Boolean,
    radiology_cancelled_ne: Boolean,
    radiology_cancelled_in: [Boolean],
    radio_cancel_date_contains: String,
    radio_cancel_date_startsWith: String,
    radio_cancel_date_endsWith: String,
    radio_cancel_date_regex: String,
    radio_cancel_date: String,
    radio_cancel_date_ne: String,
    radio_cancel_date_in: [String],
    patient_diagnoses_date_of_entry_contains: String,
    patient_diagnoses_date_of_entry_startsWith: String,
    patient_diagnoses_date_of_entry_endsWith: String,
    patient_diagnoses_date_of_entry_regex: String,
    patient_diagnoses_date_of_entry: String,
    patient_diagnoses_date_of_entry_ne: String,
    patient_diagnoses_date_of_entry_in: [String],
    patient_diagnoses_diag_type_contains: String,
    patient_diagnoses_diag_type_startsWith: String,
    patient_diagnoses_diag_type_endsWith: String,
    patient_diagnoses_diag_type_regex: String,
    patient_diagnoses_diag_type: String,
    patient_diagnoses_diag_type_ne: String,
    patient_diagnoses_diag_type_in: [String],
    patient_diagnoses_active: Boolean,
    patient_diagnoses_active: Boolean,
    patient_diagnoses_active_ne: Boolean,
    patient_diagnoses_active_in: [Boolean],
    patient_diagnoses_severity_contains: String,
    patient_diagnoses_severity_startsWith: String,
    patient_diagnoses_severity_endsWith: String,
    patient_diagnoses_severity_regex: String,
    patient_diagnoses_severity: String,
    patient_diagnoses_severity_ne: String,
    patient_diagnoses_severity_in: [String],
    patient_diagnoses_diagnosisNote_contains: String,
    patient_diagnoses_diagnosisNote_startsWith: String,
    patient_diagnoses_diagnosisNote_endsWith: String,
    patient_diagnoses_diagnosisNote_regex: String,
    patient_diagnoses_diagnosisNote: String,
    patient_diagnoses_diagnosisNote_ne: String,
    patient_diagnoses_diagnosisNote_in: [String],
    patient_diagnoses_diagnosis_contains: String,
    patient_diagnoses_diagnosis_startsWith: String,
    patient_diagnoses_diagnosis_endsWith: String,
    patient_diagnoses_diagnosis_regex: String,
    patient_diagnoses_diagnosis: String,
    patient_diagnoses_diagnosis_ne: String,
    patient_diagnoses_diagnosis_in: [String],
    patient_diagnoses_status_contains: String,
    patient_diagnoses_status_startsWith: String,
    patient_diagnoses_status_endsWith: String,
    patient_diagnoses_status_regex: String,
    patient_diagnoses_status: String,
    patient_diagnoses_status_ne: String,
    patient_diagnoses_status_in: [String],
    diagnoses_id_lt: Int,
    diagnoses_id_lte: Int,
    diagnoses_id_gt: Int,
    diagnoses_id_gte: Int,
    diagnoses_id: Int,
    diagnoses_id_ne: Int,
    diagnoses_id_in: [Int],
    diagnoses_code_contains: String,
    diagnoses_code_startsWith: String,
    diagnoses_code_endsWith: String,
    diagnoses_code_regex: String,
    diagnoses_code: String,
    diagnoses_code_ne: String,
    diagnoses_code_in: [String],
    diagnoses_type_contains: String,
    diagnoses_type_startsWith: String,
    diagnoses_type_endsWith: String,
    diagnoses_type_regex: String,
    diagnoses_type: String,
    diagnoses_type_ne: String,
    diagnoses_type_in: [String],
    diagnoses_case_contains: String,
    diagnoses_case_startsWith: String,
    diagnoses_case_endsWith: String,
    diagnoses_case_regex: String,
    diagnoses_case: String,
    diagnoses_case_ne: String,
    diagnoses_case_in: [String],
    diagnoses_parent_id_contains: String,
    diagnoses_parent_id_startsWith: String,
    diagnoses_parent_id_endsWith: String,
    diagnoses_parent_id_regex: String,
    diagnoses_parent_id: String,
    diagnoses_parent_id_ne: String,
    diagnoses_parent_id_in: [String],
    diagnoses_oi_lt: Int,
    diagnoses_oi_lte: Int,
    diagnoses_oi_gt: Int,
    diagnoses_oi_gte: Int,
    diagnoses_oi: Int,
    diagnoses_oi_ne: Int,
    diagnoses_oi_in: [Int],
    procedure_id_lt: Int,
    procedure_id_lte: Int,
    procedure_id_gt: Int,
    procedure_id_gte: Int,
    procedure_id: Int,
    procedure_id_ne: Int,
    procedure_id_in: [Int],
    procedure_name_contains: String,
    procedure_name_startsWith: String,
    procedure_name_endsWith: String,
    procedure_name_regex: String,
    procedure_name: String,
    procedure_name_ne: String,
    procedure_name_in: [String],
    procedure_icd_code_contains: String,
    procedure_icd_code_startsWith: String,
    procedure_icd_code_endsWith: String,
    procedure_icd_code_regex: String,
    procedure_icd_code: String,
    procedure_icd_code_ne: String,
    procedure_icd_code_in: [String],
    procedure_description_contains: String,
    procedure_description_startsWith: String,
    procedure_description_endsWith: String,
    procedure_description_regex: String,
    procedure_description: String,
    procedure_description_ne: String,
    procedure_description_in: [String],
    patient_procedure_id_lt: Int,
    patient_procedure_id_lte: Int,
    patient_procedure_id_gt: Int,
    patient_procedure_id_gte: Int,
    patient_procedure_id: Int,
    patient_procedure_id_ne: Int,
    patient_procedure_id_in: [Int],
    patient_procedure_request_note_contains: String,
    patient_procedure_request_note_startsWith: String,
    patient_procedure_request_note_endsWith: String,
    patient_procedure_request_note_regex: String,
    patient_procedure_request_note: String,
    patient_procedure_request_note_ne: String,
    patient_procedure_request_note_in: [String],
    patient_procedure_closing_text_contains: String,
    patient_procedure_closing_text_startsWith: String,
    patient_procedure_closing_text_endsWith: String,
    patient_procedure_closing_text_regex: String,
    patient_procedure_closing_text: String,
    patient_procedure_closing_text_ne: String,
    patient_procedure_closing_text_in: [String],
    scheduled_on_contains: String,
    scheduled_on_startsWith: String,
    scheduled_on_endsWith: String,
    scheduled_on_regex: String,
    scheduled_on: String,
    scheduled_on_ne: String,
    scheduled_on_in: [String],
    scheduled_by_contains: String,
    scheduled_by_startsWith: String,
    scheduled_by_endsWith: String,
    scheduled_by_regex: String,
    scheduled_by: String,
    scheduled_by_ne: String,
    scheduled_by_in: [String],
    patient_procedure_time_started_contains: String,
    patient_procedure_time_started_startsWith: String,
    patient_procedure_time_started_endsWith: String,
    patient_procedure_time_started_regex: String,
    patient_procedure_time_started: String,
    patient_procedure_time_started_ne: String,
    patient_procedure_time_started_in: [String],
    patient_procedure_time_start_contains: String,
    patient_procedure_time_start_startsWith: String,
    patient_procedure_time_start_endsWith: String,
    patient_procedure_time_start_regex: String,
    patient_procedure_time_start: String,
    patient_procedure_time_start_ne: String,
    patient_procedure_time_start_in: [String],
    patient_procedure_time_stop_contains: String,
    patient_procedure_time_stop_startsWith: String,
    patient_procedure_time_stop_endsWith: String,
    patient_procedure_time_stop_regex: String,
    patient_procedure_time_stop: String,
    patient_procedure_time_stop_ne: String,
    patient_procedure_time_stop_in: [String],
    patient_procedure_requested_by_contains: String,
    patient_procedure_requested_by_startsWith: String,
    patient_procedure_requested_by_endsWith: String,
    patient_procedure_requested_by_regex: String,
    patient_procedure_requested_by: String,
    patient_procedure_requested_by_ne: String,
    patient_procedure_requested_by_in: [String],
    patient_procedure_note_contains: String,
    patient_procedure_note_startsWith: String,
    patient_procedure_note_endsWith: String,
    patient_procedure_note_regex: String,
    patient_procedure_note: String,
    patient_procedure_note_ne: String,
    patient_procedure_note_in: [String],
    patient_procedure_note_time_contains: String,
    patient_procedure_note_time_startsWith: String,
    patient_procedure_note_time_endsWith: String,
    patient_procedure_note_time_regex: String,
    patient_procedure_note_time: String,
    patient_procedure_note_time_ne: String,
    patient_procedure_note_time_in: [String],
    patient_procedure_note_type_contains: String,
    patient_procedure_note_type_startsWith: String,
    patient_procedure_note_type_endsWith: String,
    patient_procedure_note_type_regex: String,
    patient_procedure_note_type: String,
    patient_procedure_note_type_ne: String,
    patient_procedure_note_type_in: [String],
    patient_procedure_request_date_contains: String,
    patient_procedure_request_date_startsWith: String,
    patient_procedure_request_date_endsWith: String,
    patient_procedure_request_date_regex: String,
    patient_procedure_request_date: String,
    patient_procedure_request_date_ne: String,
    patient_procedure_request_date_in: [String],
    patient_procedure_status_contains: String,
    patient_procedure_status_startsWith: String,
    patient_procedure_status_endsWith: String,
    patient_procedure_status_regex: String,
    patient_procedure_status: String,
    patient_procedure_status_ne: String,
    patient_procedure_status_in: [String],
    consultation_date_of_entry_contains: String,
    consultation_date_of_entry_startsWith: String,
    consultation_date_of_entry_endsWith: String,
    consultation_date_of_entry_regex: String,
    consultation_date_of_entry: String,
    consultation_date_of_entry_ne: String,
    consultation_date_of_entry_in: [String],
    consultation_diagnoses_contains: String,
    consultation_diagnoses_startsWith: String,
    consultation_diagnoses_endsWith: String,
    consultation_diagnoses_regex: String,
    consultation_diagnoses: String,
    consultation_diagnoses_ne: String,
    consultation_diagnoses_in: [String],
    consultation_note_type_contains: String,
    consultation_note_type_startsWith: String,
    consultation_note_type_endsWith: String,
    consultation_note_type_regex: String,
    consultation_note_type: String,
    consultation_note_type_ne: String,
    consultation_note_type_in: [String],
    consultation_reason_contains: String,
    consultation_reason_startsWith: String,
    consultation_reason_endsWith: String,
    consultation_reason_regex: String,
    consultation_reason: String,
    consultation_reason_ne: String,
    consultation_reason_in: [String],
    consultation_doctors_name_contains: String,
    consultation_doctors_name_startsWith: String,
    consultation_doctors_name_endsWith: String,
    consultation_doctors_name_regex: String,
    consultation_doctors_name: String,
    consultation_doctors_name_ne: String,
    consultation_doctors_name_in: [String],
    patient_procedure_nursing_task_id_contains: String,
    patient_procedure_nursing_task_id_startsWith: String,
    patient_procedure_nursing_task_id_endsWith: String,
    patient_procedure_nursing_task_id_regex: String,
    patient_procedure_nursing_task_id: String,
    patient_procedure_nursing_task_id_ne: String,
    patient_procedure_nursing_task_id_in: [String],
    patient_procedure_nursing_service_contains: String,
    patient_procedure_nursing_service_startsWith: String,
    patient_procedure_nursing_service_endsWith: String,
    patient_procedure_nursing_service_regex: String,
    patient_procedure_nursing_service: String,
    patient_procedure_nursing_service_ne: String,
    patient_procedure_nursing_service_in: [String],
    vital_sign_type_contains: String,
    vital_sign_type_startsWith: String,
    vital_sign_type_endsWith: String,
    vital_sign_type_regex: String,
    vital_sign_type: String,
    vital_sign_type_ne: String,
    vital_sign_type_in: [String],
    vital_sign_value_contains: String,
    vital_sign_value_startsWith: String,
    vital_sign_value_endsWith: String,
    vital_sign_value_regex: String,
    vital_sign_value: String,
    vital_sign_value_ne: String,
    vital_sign_value_in: [String],
    vital_sign_unit_contains: String,
    vital_sign_unit_startsWith: String,
    vital_sign_unit_endsWith: String,
    vital_sign_unit_regex: String,
    vital_sign_unit: String,
    vital_sign_unit_ne: String,
    vital_sign_unit_in: [String],
    vital_sign_min_val_contains: String,
    vital_sign_min_val_startsWith: String,
    vital_sign_min_val_endsWith: String,
    vital_sign_min_val_regex: String,
    vital_sign_min_val: String,
    vital_sign_min_val_ne: String,
    vital_sign_min_val_in: [String],
    vital_sign_read_date_contains: String,
    vital_sign_read_date_startsWith: String,
    vital_sign_read_date_endsWith: String,
    vital_sign_read_date_regex: String,
    vital_sign_read_date: String,
    vital_sign_read_date_ne: String,
    vital_sign_read_date_in: [String],
    OR: [NisaCollectionFilters],
    SORT: NisaCollectionSort,
    SORTS: [NisaCollectionSort],
    LIMIT: Int,
    SKIP: Int,
    PAGE: Int,
    PAGE_SIZE: Int,
    record_date_format: String
  ): NisaCollectionQueryResults

  getNisaCollection (
    _id: String,
    record_date_format: String
  ): NisaCollectionSingleQueryResult

`;
  
